### ISSUE TITLE
Failed to compile on MacOS when `cargo install fm-tui`

### ISSUE THREAD

**Issue by liebkne** [qkzk/fm#77]
The error looks like

```
error[E0369]: binary operation `!=` cannot be applied to type `Option<&sysinfo::Disk>`
    --> /Users/User/.cargo/registry/src/github.com-1ecc6299db9ec823/fm-tui-0.1.20/src/event_exec.rs:1510:34
     |
1510 |             if trash_mount_point != origin_mount_point {
     |                ----------------- ^^ ------------------ Option<&sysinfo::Disk>
     |                |
     |                Option<&sysinfo::Disk>

For more information about this error, try `rustc --explain E0369`.
error: could not compile `fm-tui` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `fm-tui v0.1.20`, intermediate artifacts can be found at `/var/folders/jd/0nmjhl0d5ns0qmpktsvk6nmc0000gn/T/cargo-installO30gGo`

```

**Comment by qkzk** [comment]
Hello,

I can't replicate this...
This version compiles correctly and I can install the application with no error.


You may have an obsolete version of something. May be `cargo update` then `cargo install fm-tui` will fix it.

**Comment by qkzk** [comment]
I wonder... what platform are you using ?

`Disk` doesn't implement `PartialEq` on every platform.

I guess that's why I have no problem on Linux.

**Comment by liebkne** [comment]
Hi, I'm on `macOS 13.2.1 (22D68)`.

**Comment by qkzk** [comment]
The version [0.1.21](https://github.com/qkzk/fm/releases/tag/v0.1.21) might compile on MacOS. I can't be sure since I don't have a mac.

**Comment by liebkne** [comment]
@qkzk Thanks, it complies successfully now.
